# Fancy index

In [1]:
import numpy as np

In [2]:
arr = np.random.random((8, 4))
print(arr.ndim, arr.shape)
arr


2 (8, 4)


array([[0.53959134, 0.48309019, 0.84580361, 0.51437164],
       [0.73404526, 0.22978551, 0.95890161, 0.09302189],
       [0.37162566, 0.12173777, 0.67998804, 0.86400432],
       [0.9377585 , 0.2170588 , 0.24539811, 0.48183648],
       [0.38880265, 0.30400767, 0.79310923, 0.39455708],
       [0.81200684, 0.25337494, 0.55761543, 0.70491976],
       [0.77490484, 0.84554295, 0.94546082, 0.53186913],
       [0.45240499, 0.62961523, 0.96096606, 0.33489866]])

In [3]:
[0,-1]


[0, -1]

In [4]:
arr[0][[0,-1]]


array([0.53959134, 0.51437164])

In [5]:
-arr[[4,6,1]]

array([[-0.38880265, -0.30400767, -0.79310923, -0.39455708],
       [-0.77490484, -0.84554295, -0.94546082, -0.53186913],
       [-0.73404526, -0.22978551, -0.95890161, -0.09302189]])

# reshpae

In [6]:
arr


array([[0.53959134, 0.48309019, 0.84580361, 0.51437164],
       [0.73404526, 0.22978551, 0.95890161, 0.09302189],
       [0.37162566, 0.12173777, 0.67998804, 0.86400432],
       [0.9377585 , 0.2170588 , 0.24539811, 0.48183648],
       [0.38880265, 0.30400767, 0.79310923, 0.39455708],
       [0.81200684, 0.25337494, 0.55761543, 0.70491976],
       [0.77490484, 0.84554295, 0.94546082, 0.53186913],
       [0.45240499, 0.62961523, 0.96096606, 0.33489866]])

In [7]:
arr.shape


(8, 4)

In [8]:
8*4


32

In [9]:
6*6


36

In [10]:
2*4*4


32

In [11]:
arr1 = np.arange(32).reshape((8, 4))
arr1


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [12]:
arr1 = arr.reshape((8,4))
arr1


array([[0.53959134, 0.48309019, 0.84580361, 0.51437164],
       [0.73404526, 0.22978551, 0.95890161, 0.09302189],
       [0.37162566, 0.12173777, 0.67998804, 0.86400432],
       [0.9377585 , 0.2170588 , 0.24539811, 0.48183648],
       [0.38880265, 0.30400767, 0.79310923, 0.39455708],
       [0.81200684, 0.25337494, 0.55761543, 0.70491976],
       [0.77490484, 0.84554295, 0.94546082, 0.53186913],
       [0.45240499, 0.62961523, 0.96096606, 0.33489866]])

In [13]:
arr1.shape


(8, 4)

In [14]:
arr1[[1,5,7,4]]


array([[0.73404526, 0.22978551, 0.95890161, 0.09302189],
       [0.81200684, 0.25337494, 0.55761543, 0.70491976],
       [0.45240499, 0.62961523, 0.96096606, 0.33489866],
       [0.38880265, 0.30400767, 0.79310923, 0.39455708]])

In [15]:
arr1[[1,5,7,4], [0,-1,2,3]]


array([0.73404526, 0.70491976, 0.96096606, 0.39455708])

In [16]:
arr1[[1, 5, 7, 2]]


array([[0.73404526, 0.22978551, 0.95890161, 0.09302189],
       [0.81200684, 0.25337494, 0.55761543, 0.70491976],
       [0.45240499, 0.62961523, 0.96096606, 0.33489866],
       [0.37162566, 0.12173777, 0.67998804, 0.86400432]])

In [17]:

b = arr1[[1, 5, 7, 2]]
b


array([[0.73404526, 0.22978551, 0.95890161, 0.09302189],
       [0.81200684, 0.25337494, 0.55761543, 0.70491976],
       [0.45240499, 0.62961523, 0.96096606, 0.33489866],
       [0.37162566, 0.12173777, 0.67998804, 0.86400432]])

In [18]:
b[:, [0, 3, 1, 2]]


array([[0.73404526, 0.09302189, 0.22978551, 0.95890161],
       [0.81200684, 0.70491976, 0.25337494, 0.55761543],
       [0.45240499, 0.33489866, 0.62961523, 0.96096606],
       [0.37162566, 0.86400432, 0.12173777, 0.67998804]])

In [19]:
arr


array([[0.53959134, 0.48309019, 0.84580361, 0.51437164],
       [0.73404526, 0.22978551, 0.95890161, 0.09302189],
       [0.37162566, 0.12173777, 0.67998804, 0.86400432],
       [0.9377585 , 0.2170588 , 0.24539811, 0.48183648],
       [0.38880265, 0.30400767, 0.79310923, 0.39455708],
       [0.81200684, 0.25337494, 0.55761543, 0.70491976],
       [0.77490484, 0.84554295, 0.94546082, 0.53186913],
       [0.45240499, 0.62961523, 0.96096606, 0.33489866]])

In [20]:
arr.T


array([[0.53959134, 0.73404526, 0.37162566, 0.9377585 , 0.38880265,
        0.81200684, 0.77490484, 0.45240499],
       [0.48309019, 0.22978551, 0.12173777, 0.2170588 , 0.30400767,
        0.25337494, 0.84554295, 0.62961523],
       [0.84580361, 0.95890161, 0.67998804, 0.24539811, 0.79310923,
        0.55761543, 0.94546082, 0.96096606],
       [0.51437164, 0.09302189, 0.86400432, 0.48183648, 0.39455708,
        0.70491976, 0.53186913, 0.33489866]])

In [21]:

arr1[1][2]


0.9589016137107703

In [22]:
arr.shape, arr1.shape


((8, 4), (8, 4))


# Transpose


In [23]:

arr = np.arange(16).reshape((2, 2, 4))
arr


array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [24]:
arr.shape


(2, 2, 4)

In [25]:
arr.T


array([[[ 0,  8],
        [ 4, 12]],

       [[ 1,  9],
        [ 5, 13]],

       [[ 2, 10],
        [ 6, 14]],

       [[ 3, 11],
        [ 7, 15]]])

In [26]:
a = np.random.randn(4,5)
a


array([[-0.71340536, -0.71993102,  0.47660757, -1.46107968, -0.47278209],
       [-0.42179908, -1.1195505 ,  1.22254494, -0.08420256, -0.01704719],
       [-0.75256121, -0.05331416,  1.73692058, -0.33686398, -0.30949002],
       [ 0.45485162, -0.85979042, -0.11417968, -1.65463497,  0.53559512]])

In [27]:
a[0][0] = np.nan
a[1][0] = np.nan
a[2][0] = np.nan
np.isnan(a)


array([[ True, False, False, False, False],
       [ True, False, False, False, False],
       [ True, False, False, False, False],
       [False, False, False, False, False]])

In [28]:
cond = np.isnan(a)
cond


array([[ True, False, False, False, False],
       [ True, False, False, False, False],
       [ True, False, False, False, False],
       [False, False, False, False, False]])

In [29]:
np.floor_divide(a,3)


C:\Users\Karar\AppData\Local\Temp\ipykernel_3156\3381902353.py:1: RuntimeWarning: invalid value encountered in floor_divide
  np.floor_divide(a,3)


array([[nan, -1.,  0., -1., -1.],
       [nan, -1.,  0., -1., -1.],
       [nan, -1.,  0., -1., -1.],
       [ 0., -1., -1., -1.,  0.]])

In [30]:
np.power(a,2)


array([[           nan, 5.18300669e-01, 2.27154771e-01, 2.13475384e+00,
        2.23522902e-01],
       [           nan, 1.25339332e+00, 1.49461614e+00, 7.09007170e-03,
        2.90606724e-04],
       [           nan, 2.84239943e-03, 3.01689309e+00, 1.13477341e-01,
        9.57840751e-02],
       [2.06889996e-01, 7.39239561e-01, 1.30369987e-02, 2.73781688e+00,
        2.86862135e-01]])

In [31]:
np.divide(a,3)


array([[        nan, -0.23997701,  0.15886919, -0.48702656, -0.15759403],
       [        nan, -0.3731835 ,  0.40751498, -0.02806752, -0.0056824 ],
       [        nan, -0.01777139,  0.57897353, -0.11228799, -0.10316334],
       [ 0.15161721, -0.28659681, -0.03805989, -0.55154499,  0.17853171]])

In [32]:
np.sign(a)


array([[nan, -1.,  1., -1., -1.],
       [nan, -1.,  1., -1., -1.],
       [nan, -1.,  1., -1., -1.],
       [ 1., -1., -1., -1.,  1.]])

# gridmesh


In [33]:
points = np.arange(-5, 5, 0.01)
points.shape


(1000,)

In [34]:
xs, ys = np.meshgrid(points, points)
xs.shape, ':', ys.shape


((1000, 1000), ':', (1000, 1000))

In [35]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])

cond = np.array([True, False, True, True, False])

xarr +yarr


array([3.2, 3.4, 3.6, 3.8, 4. ])

# List comprehension

In [36]:
for x,y in zip(xarr, yarr):
    print(x+y)


3.2
3.4000000000000004
3.5999999999999996
3.8
4.0


In [37]:
for x in xarr:
    print('outer',x)
    for y in yarr:
        print('inner',x,y)



outer 1.1
inner 1.1 2.1
inner 1.1 2.2
inner 1.1 2.3
inner 1.1 2.4
inner 1.1 2.5
outer 1.2
inner 1.2 2.1
inner 1.2 2.2
inner 1.2 2.3
inner 1.2 2.4
inner 1.2 2.5
outer 1.3
inner 1.3 2.1
inner 1.3 2.2
inner 1.3 2.3
inner 1.3 2.4
inner 1.3 2.5
outer 1.4
inner 1.4 2.1
inner 1.4 2.2
inner 1.4 2.3
inner 1.4 2.4
inner 1.4 2.5
outer 1.5
inner 1.5 2.1
inner 1.5 2.2
inner 1.5 2.3
inner 1.5 2.4
inner 1.5 2.5


In [38]:

for x in zip(xarr, yarr, cond):
    print(x)
a = []


(1.1, 2.1, True)
(1.2, 2.2, False)
(1.3, 2.3, True)
(1.4, 2.4, True)
(1.5, 2.5, False)


In [39]:

for i in range(10):
    if i > 5:
        a.append(i)
a


[6, 7, 8, 9]

In [40]:
[i if i>5 else 0 for i in range(10)] ## this is actual list compreh
xarr


array([1.1, 1.2, 1.3, 1.4, 1.5])

In [41]:

np.where(xarr>1.2, 0, 100)


array([100, 100,   0,   0,   0])

In [42]:
np.where(cond, xarr, yarr)


array([1.1, 2.2, 1.3, 1.4, 2.5])

In [43]:
arr = np.random.randn(4, 4)
arr


array([[-0.87787646,  0.2524861 , -0.15809364, -0.72941295],
       [ 0.04082421,  0.26460293, -0.35953481, -1.11022668],
       [-1.11048056,  1.21985416,  0.12576449, -0.41061878],
       [-0.37111871, -0.82480883,  0.97304127, -0.26317173]])

In [44]:
(arr <0).sum()


10

In [45]:
cond = arr < 0
cond


array([[ True, False,  True,  True],
       [False, False,  True,  True],
       [ True, False, False,  True],
       [ True,  True, False,  True]])

In [46]:
np.where(arr < 0,
        0,
        arr)


array([[0.        , 0.2524861 , 0.        , 0.        ],
       [0.04082421, 0.26460293, 0.        , 0.        ],
       [0.        , 1.21985416, 0.12576449, 0.        ],
       [0.        , 0.        , 0.97304127, 0.        ]])

In [47]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.unique(names)


array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [51]:
{1,2,3,1,2,3,1,2,3}
a


[6, 7, 8, 9]

In [49]:
np.save('myfile',a)
np.load('myfile.npy')


array([6, 7, 8, 9])

# ML


In [53]:
a =  np.array(a)

In [54]:
a*a


array([36, 49, 64, 81])

In [55]:
a


array([6, 7, 8, 9])

In [56]:
np.random.shuffle(a)
a


array([8, 6, 9, 7])

In [57]:
np.abs(a)


array([8, 6, 9, 7])

In [ ]:
a = [1,2,3,4,5,6,7,8,9]


