- Table 4-1. Array creation functions
- Table 4-2. NumPy data types
- 92 | Chapter 4: NumPy Basics: Arrays and Vectorized Computation


In [1]:
import numpy as np

In [3]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
a.dtype

dtype('int32')

In [6]:
%time for _ in range(10): a = a * 2


CPU times: total: 0 ns
Wall time: 0 ns


In [19]:
np.random.seed(42)

In [38]:
np.random.seed(42)
b = np.random.randn(5,3)
b

array([[ 0.49671415, -0.1382643 ,  0.64768854],
       [ 1.52302986, -0.23415337, -0.23413696],
       [ 1.57921282,  0.76743473, -0.46947439],
       [ 0.54256004, -0.46341769, -0.46572975],
       [ 0.24196227, -1.91328024, -1.72491783]])

In [40]:
b.shape, b.dtype

((5, 3), dtype('float64'))

In [29]:
a = np.random.random(5)

In [26]:
np.random.randint(10,100)

61

In [30]:
a

array([0.90779209, 0.80721621, 0.22014597, 0.00636195, 0.99707958])

In [31]:
a*10

array([9.07792092, 8.07216214, 2.20145972, 0.06361954, 9.9707958 ])

In [33]:
a-100

array([-99.09220791, -99.19278379, -99.77985403, -99.99363805,
       -99.00292042])

In [35]:
a**a

array([0.91592599, 0.84124156, 0.71663896, 0.96833704, 0.9970881 ])

In [36]:
a.dtype

dtype('float64')

In [37]:
a.shape

(5,)

In [41]:
data1 = [6, 7.5, 8, 0, 1]


In [43]:
a = np.array(data1)
a

array([6. , 7.5, 8. , 0. , 1. ])

In [44]:
a.shape, a.dtype

((5,), dtype('float64'))

In [46]:
a.min()

0.0

In [47]:
a.std()

3.3466401061363023

In [48]:
a.mean()

4.5

In [51]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]

b = np.array(data2)
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [53]:
b.shape

(2, 4)

In [54]:
b.ndim

2

In [1]:
import numpy as np

In [1]:
import numpy as np
np.empty(100)

array([0.00000000e+000, 6.95176294e-310, 3.68078906e-321,             nan,
       9.08367229e+223, 0.00000000e+000, 3.77704695e+233, 7.22756687e+159,
       1.10639950e+200, 3.64726544e+180, 1.87750993e-152, 4.82336277e+228,
       9.23528171e+242, 2.52960802e-258, 4.47593816e-091, 1.76353931e-070,
       8.63819469e-096, 7.12930810e+159, 2.61191759e+209, 2.25020976e+223,
       1.67640691e+243, 1.24595996e-089, 1.74593501e+238, 1.13556093e-153,
       1.96088695e+243, 9.82391603e+252, 3.62479391e+228, 1.32655511e-258,
       7.22082943e+159, 6.03433819e-154, 2.35570319e+251, 4.77800043e+180,
       5.80426330e+180, 2.19980343e-152, 1.12038868e+219, 2.31881454e-152,
       6.01346953e-154, 5.82147482e+180, 6.12486739e+257, 4.47593784e-091,
       1.45291304e-094, 1.62596915e-086, 1.43615024e+161, 6.01334682e-154,
       2.59345433e+161, 6.72801012e+199, 9.13601355e+242, 1.48504071e+161,
       1.45913393e-152, 1.12044105e+219, 2.63422477e-085, 3.88281160e+233,
       1.27966001e-152, 1

In [2]:
c = np.empty((2, 3, 2))
c

array([[[7.43691643e-312, 3.16202013e-322],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 1.92104934e-052]],

       [[2.12862920e-052, 2.21264407e-052],
        [9.27946110e-072, 6.89492046e-042],
        [4.75285352e-037, 1.08712798e-071]]])

In [4]:
c.ndim, c.shape

(3, (2, 3, 2))

In [6]:
tt = np.asarray(c)
tt

array([[[7.43691643e-312, 3.16202013e-322],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 1.92104934e-052]],

       [[2.12862920e-052, 2.21264407e-052],
        [9.27946110e-072, 6.89492046e-042],
        [4.75285352e-037, 1.08712798e-071]]])

In [18]:
o = np.ones_like(c, dtype=np.int8)
o

array([[[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]]], dtype=int8)

In [11]:
o.ndim, o.shape

(3, (2, 3, 2))

In [14]:
np.full(10,'a')

array(['a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a'], dtype='<U1')

In [19]:
a = np.eye(4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [20]:
a.ndim, a.dtype,a.shape

(2, dtype('float64'), (4, 4))

In [21]:
a1 = a.astype(np.int16)
a1.ndim, a1.dtype,a1.shape

(2, dtype('int16'), (4, 4))

In [23]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
arr_slice = arr[5:8] # this is just a reflexion of arr
# its not a copy
arr22 = arr.copy()
arr_slice

array([    5, 12345,     7])

In [28]:
arr_slice[1] = 12345
arr22[1] = 55

In [29]:
arr

array([    0,     1,     2,     3,     4,     5, 12345,     7,     8,
           9])

In [30]:
arr22

array([    0,    55,     2,     3,     4,     5, 12345,     7,     8,
           9])

In [31]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [32]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [38]:
arr2d[-1,-1]

9

In [34]:
arr2d.shape

(3, 3)

In [39]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
arr2d[1:,1:]

array([[5, 6],
       [8, 9]])