## Important tables
- Table 4-1. Array creation functions
- Table 4-2. NumPy data types
- 92 | Chapter 4: NumPy Basics: Arrays and Vectorized Computation


In [1]:
import numpy as np

In [6]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [5]:
a = np.arange(10)
a

array([2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
a.dtype

dtype('int32')

In [6]:
%time for _ in range(10): a = a * 2

CPU times: total: 0 ns
Wall time: 0 ns


In [19]:
np.random.seed(42)

In [7]:
np.random.seed(42)
b = np.random.randn(5,3)
b

array([[ 0.49671415, -0.1382643 ,  0.64768854],
       [ 1.52302986, -0.23415337, -0.23413696],
       [ 1.57921282,  0.76743473, -0.46947439],
       [ 0.54256004, -0.46341769, -0.46572975],
       [ 0.24196227, -1.91328024, -1.72491783]])

In [8]:
b.shape, b.dtype

((5, 3), dtype('float64'))

In [12]:
a = np.random.random((10,5))
a

array([[0.66252228, 0.31171108, 0.52006802, 0.54671028, 0.18485446],
       [0.96958463, 0.77513282, 0.93949894, 0.89482735, 0.59789998],
       [0.92187424, 0.0884925 , 0.19598286, 0.04522729, 0.32533033],
       [0.38867729, 0.27134903, 0.82873751, 0.35675333, 0.28093451],
       [0.54269608, 0.14092422, 0.80219698, 0.07455064, 0.98688694],
       [0.77224477, 0.19871568, 0.00552212, 0.81546143, 0.70685734],
       [0.72900717, 0.77127035, 0.07404465, 0.35846573, 0.11586906],
       [0.86310343, 0.62329813, 0.33089802, 0.06355835, 0.31098232],
       [0.32518332, 0.72960618, 0.63755747, 0.88721274, 0.47221493],
       [0.11959425, 0.71324479, 0.76078505, 0.5612772 , 0.77096718]])

In [13]:
np.random.randint(10,100)

36

## Arithmetic operations

In [30]:
a

array([0.90779209, 0.80721621, 0.22014597, 0.00636195, 0.99707958])

In [31]:
a*10

array([9.07792092, 8.07216214, 2.20145972, 0.06361954, 9.9707958 ])

In [33]:
a-100

array([-99.09220791, -99.19278379, -99.77985403, -99.99363805,
       -99.00292042])

In [35]:
a**a

array([0.91592599, 0.84124156, 0.71663896, 0.96833704, 0.9970881 ])

In [36]:
a.dtype

dtype('float64')

In [37]:
a.shape

(5,)

## Creating NumPy Array from python sequential datatypes

In [14]:
data1 = [6, 7.5, 8, 0, 1]


In [20]:
a = np.array((4,5,6,7))
a

array([4, 5, 6, 7])

In [21]:
a.shape, a.dtype

((4,), dtype('int32'))

## Few stat methods for arrays in NumPy

In [46]:
a.min()

0.0

In [47]:
a.std()

3.3466401061363023

In [48]:
a.mean()

4.5

In [59]:
b1

array([22,  2,  3,  4])

In [61]:
a

array([4, 5, 6, 7])

- Table 4-1. Array creation function
- **ones_like** : produces a ones array of the same shape and dtype

In [76]:
c = np.ones_like(data2,  dtype=np.float64)
c

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [77]:
c[0][0] = -88
c[1][1] = -55
c #-256 +256

array([[-88.,   1.,   1.,   1.],
       [  1., -55.,   1.,   1.]])

In [82]:
import pandas as pd

In [85]:
a = pd.DataFrame([[1,2,3],[3,2,1]])
print(a)

   0  1  2
0  1  2  3
1  3  2  1


In [84]:
a.values

array([[1, 2, 3],
       [3, 2, 1]], dtype=int64)

## Type casting

In [81]:
c.astype(np.uint8)

array([[168,   1,   1,   1],
       [  1, 201,   1,   1]], dtype=uint8)

## declare type at time of creating array

In [80]:
np.array(c, dtype=np.int8) # 0 +256

array([[-88,   1,   1,   1],
       [  1, -55,   1,   1]], dtype=int8)

In [68]:
c.dtype

dtype('float64')

# 2-dimensional array

In [2]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]

b = np.array(data2)
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [6]:
'dimention->',b.ndim,'shape->', b.shape

('dimention->', 2, 'shape->', (2, 4))

### Creating a new array using previous array shape, dtype and values (You can say it is a copy of previous array)

In [7]:
b2 = [1,2,3,4]
b1 = np.asarray(b2)
b1

array([1, 2, 3, 4])

In [9]:
b1[0]=22  ## as we can see changing value in array 'b1' does not 
b2        ## changes orignal array 'b2'

[1, 2, 3, 4]

In [51]:
b1

array([[22,  2,  3,  4],
       [ 5,  6,  7,  8]])

In [54]:
b.ndim

2

In [46]:
b

array([0.00000000e+000, 6.95215641e-310, 3.78454285e-321,             nan,
       1.15998412e-028, 4.31603868e-080, 1.94919985e-153, 1.35717430e+131,
       7.86208518e-067, 3.66914704e-062, 1.13241561e-095, 1.10764612e-047,
       1.57588666e-052, 1.13278065e-095, 2.52701367e-052, 1.81148490e-152,
       9.37041222e-076, 1.38347858e-047, 2.42381636e-052, 6.98348281e-077,
       4.66526737e-033, 4.01769094e-057, 6.98350245e-077, 4.85787210e-033,
       6.01391519e-154, 2.90708441e-033, 9.45516471e-096, 3.89415473e-033,
       8.54289868e-072, 1.04024584e-095, 6.75365860e-067, 3.66914704e-062,
       9.14572590e+140, 6.01347002e-154, 7.11171835e-038, 6.98352878e-077,
       2.17665182e-076, 5.35421654e-038, 6.98347614e-077, 4.66917545e-062,
       2.08960884e-076, 1.03080385e+136, 6.01347002e-154, 4.27481512e-033,
       8.54289868e-072, 8.51882930e-096, 3.31183843e-033, 1.30354289e-076,
       9.46245120e-096, 7.11520718e-038, 1.81148490e-152, 9.37041222e-076,
       9.05973803e-043, 7

## Usually values are zero when we create arry by np.empty() BUT sometime it uses the garbage values from the memory 

In [23]:
import numpy as np
b = np.empty(100)
b

array([0.00000000e+000, 6.95215641e-310, 3.78454285e-321,             nan,
       1.15998412e-028, 4.31603868e-080, 1.94919985e-153, 1.35717430e+131,
       7.86208518e-067, 3.66914704e-062, 1.13241561e-095, 1.10764612e-047,
       1.57588666e-052, 1.13278065e-095, 2.52701367e-052, 1.81148490e-152,
       9.37041222e-076, 1.38347858e-047, 2.42381636e-052, 6.98348281e-077,
       4.66526737e-033, 4.01769094e-057, 6.98350245e-077, 4.85787210e-033,
       6.01391519e-154, 2.90708441e-033, 9.45516471e-096, 3.89415473e-033,
       8.54289868e-072, 1.04024584e-095, 6.75365860e-067, 3.66914704e-062,
       9.14572590e+140, 6.01347002e-154, 7.11171835e-038, 6.98352878e-077,
       2.17665182e-076, 5.35421654e-038, 6.98347614e-077, 4.66917545e-062,
       2.08960884e-076, 1.03080385e+136, 6.01347002e-154, 4.27481512e-033,
       8.54289868e-072, 8.51882930e-096, 3.31183843e-033, 1.30354289e-076,
       9.46245120e-096, 7.11520718e-038, 1.81148490e-152, 9.37041222e-076,
       9.05973803e-043, 7

In [24]:
b.shape

(100,)

In [41]:
c = np.empty((2, 3, 2)) ## 3-D array
c

array([[[9.90000000e+001, 3.16202013e-322],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 1.19943272e-071]],

       [[1.69062002e-052, 1.00371587e-042],
        [1.74039953e+184, 1.42416690e+160],
        [9.77378047e+165, 8.01201168e+165]]])

In [42]:
c.ndim, c.shape

(3, (2, 3, 2))

In [40]:
np.copy(c) 

array([[[9.90000000e+001, 3.16202013e-322],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 1.19943272e-071]],

       [[1.69062002e-052, 1.00371587e-042],
        [1.74039953e+184, 1.42416690e+160],
        [9.77378047e+165, 8.01201168e+165]]])

#### To see difference in np.asarray() AND np.copy() refer to following link and go through the verfied green tick answer
https://stackoverflow.com/questions/14415741/what-is-the-difference-between-np-array-and-np-asarray

In [43]:
tt = np.asarray(c)
tt

array([[[9.90000000e+001, 3.16202013e-322],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 1.19943272e-071]],

       [[1.69062002e-052, 1.00371587e-042],
        [1.74039953e+184, 1.42416690e+160],
        [9.77378047e+165, 8.01201168e+165]]])

In [44]:
tt[0][0][0] = 555

In [45]:
c

array([[[5.55000000e+002, 3.16202013e-322],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 1.19943272e-071]],

       [[1.69062002e-052, 1.00371587e-042],
        [1.74039953e+184, 1.42416690e+160],
        [9.77378047e+165, 8.01201168e+165]]])

In [38]:
tt

array([[[9.90000000e+001, 3.16202013e-322],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 1.19943272e-071]],

       [[1.69062002e-052, 1.00371587e-042],
        [1.74039953e+184, 1.42416690e+160],
        [9.77378047e+165, 8.01201168e+165]]])

### NumPy funcitnos to create different arrays

In [18]:
o = np.ones_like(c, dtype=np.int8)
o

array([[[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]]], dtype=int8)

In [11]:
o.ndim, o.shape

(3, (2, 3, 2))

In [14]:
np.full(10,'a')

array(['a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a'], dtype='<U1')

In [19]:
a = np.eye(4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [20]:
a.ndim, a.dtype,a.shape

(2, dtype('float64'), (4, 4))

In [21]:
a1 = a.astype(np.int16)
a1.ndim, a1.dtype,a1.shape

(2, dtype('int16'), (4, 4))

In [23]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
arr_slice = arr[5:8] # this is just a reflexion of arr
# its not a copy
arr22 = arr.copy()
arr_slice

array([    5, 12345,     7])

In [28]:
arr_slice[1] = 12345
arr22[1] = 55

In [29]:
arr

array([    0,     1,     2,     3,     4,     5, 12345,     7,     8,
           9])

In [30]:
arr22

array([    0,    55,     2,     3,     4,     5, 12345,     7,     8,
           9])

In [31]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [32]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [38]:
arr2d[-1,-1]

9

In [34]:
arr2d.shape

(3, 3)

In [39]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
arr2d[1:,1:]

array([[5, 6],
       [8, 9]])

## Filter/query data based on condition

In [89]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
names.shape

(7,)

In [90]:
data = np.random.randn(7, 4)
data

array([[-0.42064532, -0.34271452, -0.80227727, -0.16128571],
       [ 0.40405086,  1.8861859 ,  0.17457781,  0.25755039],
       [-0.07444592, -1.91877122, -0.02651388,  0.06023021],
       [ 2.46324211, -0.19236096,  0.30154734, -0.03471177],
       [-1.16867804,  1.14282281,  0.75193303,  0.79103195],
       [-0.90938745,  1.40279431, -1.40185106,  0.58685709],
       [ 2.19045563, -0.99053633, -0.56629773,  0.09965137]])

In [113]:
data > 0

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [False, False, False,  True],
       [ True, False,  True, False],
       [False,  True,  True,  True],
       [False,  True, False,  True],
       [ True, False, False,  True]])

In [ ]:
data [0][1]

In [116]:
data[data > 0] = 0
data

array([[-0.42064532, -0.34271452, -0.80227727, -0.16128571],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [-0.07444592, -1.91877122, -0.02651388,  0.        ],
       [ 0.        , -0.19236096,  0.        , -0.03471177],
       [-1.16867804,  0.        ,  0.        ,  0.        ],
       [-0.90938745,  0.        , -1.40185106,  0.        ],
       [ 0.        , -0.99053633, -0.56629773,  0.        ]])

In [110]:
~(names == 'Bob')

array([False,  True,  True, False,  True,  True,  True])

In [98]:
bol_bob = np.array([ True, False, False,  True, False, False,True])
bol_bob

array([ True, False, False,  True, False, False,  True])

In [107]:
tt = data[bol_bob, 1]
tt

array([-0.34271452, -0.19236096, -0.99053633])

In [ ]:
names == 'Bob'

In [109]:
~(0)

-1

In [105]:
tt [:, -1]

array([-0.16128571, -0.03471177,  0.09965137])

In [91]:
data[0]

array([-0.42064532, -0.34271452, -0.80227727, -0.16128571])