In [1]:
import numpy as np

In [2]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])

cond = np.array([True, False, True, True, False])

In [ ]:
'karar'

In [7]:
[x if c else y for x,y,c in zip(xarr,yarr,cond)]

[1.1, 2.2, 1.3, 1.4, 2.5]

In [13]:
np.where(cond, xarr, yarr)

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [14]:
xarr.mean()

1.3

In [19]:
a = np.random.random((4,4))
a

array([[0.32044548, 0.28127775, 0.8738072 , 0.99547885],
       [0.65036675, 0.04515635, 0.67266606, 0.45287251],
       [0.63074558, 0.11567403, 0.12983885, 0.54490871],
       [0.42610845, 0.08030012, 0.16957135, 0.50714211]])

In [22]:
a[0,1] =  np.nan
a[2,1] =  np.nan

In [23]:
a

array([[0.32044548,        nan, 0.8738072 , 0.99547885],
       [0.65036675, 0.04515635, 0.67266606, 0.45287251],
       [0.63074558,        nan, 0.12983885, 0.54490871],
       [0.42610845, 0.08030012, 0.16957135, 0.50714211]])

In [26]:
import pandas as pd

In [43]:
b = pd.DataFrame(a)
b

0         1         2         3
0  0.320445       NaN  0.873807  0.995479
1  0.650367  0.045156  0.672666  0.452873
2  0.630746       NaN  0.129839  0.544909
3  0.426108  0.080300  0.169571  0.507142

In [46]:
b == np.NaN

0      1      2      3
0  False  False  False  False
1  False  False  False  False
2  False  False  False  False
3  False  False  False  False

In [48]:
b.values

array([[0.32044548,        nan, 0.8738072 , 0.99547885],
       [0.65036675, 0.04515635, 0.67266606, 0.45287251],
       [0.63074558,        nan, 0.12983885, 0.54490871],
       [0.42610845, 0.08030012, 0.16957135, 0.50714211]])

In [49]:
b.fillna(b.mean())

0         1         2         3
0  0.320445  0.062728  0.873807  0.995479
1  0.650367  0.045156  0.672666  0.452873
2  0.630746  0.062728  0.129839  0.544909
3  0.426108  0.080300  0.169571  0.507142

In [47]:
np.where(b.isna(), b.mean(), b)

array([[0.32044548, 0.06272823, 0.8738072 , 0.99547885],
       [0.65036675, 0.04515635, 0.67266606, 0.45287251],
       [0.63074558, 0.06272823, 0.12983885, 0.54490871],
       [0.42610845, 0.08030012, 0.16957135, 0.50714211]])

In [45]:
b.isna()

0      1      2      3
0  False   True  False  False
1  False  False  False  False
2  False   True  False  False
3  False  False  False  False

In [40]:
0 + np.NaN

nan

In [25]:
a[:,1].mean()

nan

In [ ]:
np.where(arr == np.nan, xarr.mean(), )

In [51]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])


In [52]:
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [87]:
np.array([[10000,500,2,'bad'],[40000,800,4,'good']])

array([['10000', '500', '2', 'bad'],
       ['40000', '800', '4', 'good']], dtype='<U11')

# Pandas (series)

In [57]:
from pandas import Series, DataFrame 

In [66]:
obj2 = pd.Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [62]:
obj2['a'] = np.nan
obj2

d    4.0
b    7.0
a    NaN
c    3.0
dtype: float64

In [64]:
obj2.mean()

4.666666666666667

In [65]:
np.mean(np.array([1,2,3,np.nan]))

nan

In [63]:
np.mean(obj2)

4.666666666666667

In [67]:
np.abs(obj2)

d    4
b    7
a    5
c    3
dtype: int64

In [73]:
t = pd.DataFrame([[1,0,3],[4,5]], columns=['one','two','three'])
t

one  two  three
0    1    0    3.0
1    4    5    NaN

In [74]:
t['two'] + t['three']

0    3.0
1    NaN
dtype: float64

In [ ]:
pd.isna()

In [ ]:
pd.isnull()

# DataFrame

In [81]:
d1 = {'one':pd.Series([1,2,3]), 'two':pd.Series(['4','5','6'])}

In [82]:
d1

{'one': 0    1
 1    2
 2    3
 dtype: int64,
 'two': 0    4
 1    5
 2    6
 dtype: object}

In [99]:
d1.values()

dict_values([0    1
1    2
2    3
dtype: int64, 0    4
1    5
2    6
dtype: object])

In [106]:
g1 = pd.DataFrame([[1,2],[5,6]], columns=['hh first','tt',])
g1

hh first  tt
0         1   2
1         5   6

In [109]:
g1['hh first']

0    1
1    5
Name: hh first, dtype: int64

In [105]:
pd.DataFrame(g1, columns=['tt','uu','hh'])

tt  uu  hh
0   2 NaN   1
1   6 NaN   5

In [86]:
g1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   one     3 non-null      int64 
 1   two     3 non-null      object
dtypes: int64(1), object(1)
memory usage: 176.0+ bytes


In [88]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
 'year': [2000, 2001, 2002, 2001, 2002, 2003],
 'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}

In [89]:
frame = pd.DataFrame(data)

In [91]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [96]:
frame.tail()

state  year  pop
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [122]:
frame.iloc[4]

state    Nevada
year       2002
pop         2.9
Name: 4, dtype: object

In [169]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
 'year': [2000, 2001, 2002, 2001, 2002, 2003],
 'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}


In [170]:
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'],
                        index=[1, 4, 'three', 'four','five', 'six'])


In [ ]:
0,1,2,3,4,5,6

In [112]:
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [115]:
frame2.iloc[4]

year       2002
state    Nevada
pop         2.9
debt        NaN
Name: five, dtype: object

In [113]:
frame2.loc['four']

year       2001
state    Nevada
pop         2.4
debt        NaN
Name: four, dtype: object

In [172]:
frame2.debt = 1.6
frame2

year   state  pop  debt
1      2000    Ohio  1.5   1.6
4      2001    Ohio  1.7   1.6
three  2002    Ohio  3.6   1.6
four   2001  Nevada  2.4   1.6
five   2002  Nevada  2.9   1.6
six    2003  Nevada  3.2   1.6

In [124]:
val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])
val

two    -1.2
four   -1.5
five   -1.7
dtype: float64

In [147]:
c = frame2['debt'].values
c

array([ nan, -1.2,  nan, -1.5, -1.7,  nan])

In [167]:
type(np.nan)

float

In [165]:
c[0] ==  np.NAN

False

In [168]:
np.where(c<0, 66, c)

C:\Users\Karar\AppData\Local\Temp\ipykernel_9024\2306849814.py:1: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  np.where(c==np.float64, 66, c)


array([ nan, -1.2,  nan, -1.5, -1.7,  nan])

In [173]:
frame2

year   state  pop  debt
1      2000    Ohio  1.5   1.6
4      2001    Ohio  1.7   1.6
three  2002    Ohio  3.6   1.6
four   2001  Nevada  2.4   1.6
five   2002  Nevada  2.9   1.6
six    2003  Nevada  3.2   1.6

In [174]:
frame2['debt1'] = val
frame2

year   state  pop  debt  debt1
1      2000    Ohio  1.5   1.6    NaN
4      2001    Ohio  1.7   1.6    NaN
three  2002    Ohio  3.6   1.6    NaN
four   2001  Nevada  2.4   1.6   -1.5
five   2002  Nevada  2.9   1.6   -1.7
six    2003  Nevada  3.2   1.6    NaN

In [181]:
frame2['debt1'][b]

four   -1.5
five   -1.7
Name: debt1, dtype: float64

In [183]:
frame2['debt'][b] = frame2['debt1'][b].copy()

C:\Users\Karar\AppData\Local\Temp\ipykernel_9024\3843867627.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  frame2['debt'][b] = frame2['debt1'][b].copy()


In [184]:
frame2

year   state  pop  debt  debt1
1      2000    Ohio  1.5   1.6    NaN
4      2001    Ohio  1.7   1.6    NaN
three  2002    Ohio  3.6   1.6    NaN
four   2001  Nevada  2.4  -1.5   -1.5
five   2002  Nevada  2.9  -1.7   -1.7
six    2003  Nevada  3.2   1.6    NaN

In [185]:
del frame2['debt1']

In [186]:
frame2

year   state  pop  debt
1      2000    Ohio  1.5   1.6
4      2001    Ohio  1.7   1.6
three  2002    Ohio  3.6   1.6
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   1.6

In [178]:
b = frame2['debt1'].notna().values
b

array([False, False, False,  True,  True, False])

In [155]:
frame2.loc['one']['debt']

nan

In [154]:
type(frame2.loc['one']['debt'])

numpy.float64

In [144]:
frame2.fillna(66)

year   state  pop  debt
one    2000    Ohio  1.5  66.0
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6  66.0
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2  66.0

In [140]:
a = frame2.isna().values[:,-1]
a

array([ True, False,  True, False, False,  True])

In [141]:
frame2.loc[a,'debt'] = 66

In [142]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5  66.0
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6  66.0
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2  66.0

# Table 5-1. Possible data inputs to DataFrame constructor


In [ ]:
a = frame2.copy()

In [187]:
pd.DataFrame(frame2)

year   state  pop  debt
1      2000    Ohio  1.5   1.6
4      2001    Ohio  1.7   1.6
three  2002    Ohio  3.6   1.6
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   1.6